# -*- coding: utf-8 -*-
"""calcule spectrogrammes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cC93G0yl2o5qxAuTaBGg6yBhoUdecdvj
"""

import os
import librosa
import librosa.display
import numpy as np
import matplotlib.pyplot as plt
import time

#Get all wav audio files from directory (and subdirectories)

audio_dir = '/baie/travail/guyot/MRM/data/sliced_audio/audio_cut/2013_05_16-23_15_00'

files_path = []
files_name = []
for path, subdirs, files in os.walk(audio_dir):
    for name in files: 
        if name.endswith(".wav"):
            files_path.append(os.path.join(path, name))
            files_name.append(name)
print("-", len(files_name), "files found in the directory", audio_dir)

files_dir= '/baie/travail/guyot/MRM/data/sliced_audio/audio_cut/' 
features_dir = '/baie/travail/guyot/MRM/data/spectrogrammes/2013_05_16-23_15_00/'
 
for file_path, file_name in zip(files_path, files_name): 
    
    feature_file_name = features_dir + os.path.splitext(file_name)[0] + '.txt'
    
    
    print("Compute features from file:", file_name)
    y, sr = librosa.load(file_path)
    features = librosa.feature.melspectrogram(y=y, sr=sr)
    
    features.tofile(feature_file_name)
    
    np.savetxt(feature_file_name, features)

    
print('Features successfully computed')

